### ISSUE TITLE
Some missing features

### ISSUE THREAD

**Issue by X-X3** [intellij-v/intellij-v#246]
- [ ] WSL toolchain support
- [ ] IDE 'structure' overview
- [ ] More distinguishable colors of correct semantic of grammars

**Comment by i582** [comment]
For Structure view see https://github.com/i582/vlang-idea/commit/80eea186c551d197e99efc9ed747854f17cccf50 and https://plugins.jetbrains.com/plugin/20287-vlang/docs/navigation-and-search.html#file-structure

**Comment by i582** [comment]
You can suggest your own color scheme, I will be glad to hear your suggestions

**Comment by i582** [comment]
I will close this issue due to lack of activity, the issue about WSL was created separately. The other two points have already been made.

https://github.com/intellij-v/intellij-v/issues/493
