### ISSUE TITLE
A pointer type structure is not recognized

### ISSUE THREAD

**Issue by 32ns** [intellij-v/intellij-v#324]
### Describe the bug

pub struct FF {
	format_ctx &ffmpeg.AVFormatContext
        streams    &&ffmpeg.AVStream
}

### Expected Behavior

The plug-in does not recognize this type of syntax

### Current Behavior

The plug-in does not recognize this type of syntax

### Reproduction Steps

The plug-in does not recognize this type of syntax

### Environment details (`v doctor` output)

The plug-in does not recognize this type of syntax

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

goland

**Comment by i582** [comment]
What do you mean? It seems the plugin is successfully parsing this code and in my case it just can't find the required package. Please, show a screenshot from the IDE.

<img width="437" alt="Снимок экрана 2022-12-18 в 00 07 13" src="https://user-images.githubusercontent.com/51853996/208264268-bddb8a49-bdac-48b8-b17a-cf29b47bc3f2.png">

**Comment by 32ns** [comment]
ff:=FF{}
ff.
There is no code prompt for instantiated variables

**Comment by i582** [comment]
oh, I see, can you provide the whole file in which this happens?

**Comment by 32ns** [comment]
https://drive.google.com/file/d/19P6ktOwYD_AVzIs7xGZ6SOL4NbDM0sO9/view?usp=share_link
I uploaded the google drive, please have a look
![image](https://user-images.githubusercontent.com/1725120/208313009-9a42ed13-226f-455c-80d7-cba33346b9ec.png)

**Comment by i582** [comment]
Hi
Thanks for report!
Fixed.
Today is beta.2 release.
