### ISSUE TITLE
After installing this plugin you can't debug any java application

### ISSUE THREAD

**Issue by angel-git** [intellij-v/intellij-v#369]
### Describe the bug

when this plugin is installed you can't run java applications in debug mode.

### Expected Behavior

The plugin shouldn't break anything :)

### Current Behavior

you can't run java applications in debug mode.

### Reproduction Steps

With the plugin installed
- create a new empty java project:
![image](https://user-images.githubusercontent.com/1565058/210315568-31838ed0-13fd-4c43-a9e3-3e8cfe55f81e.png)
- click on run
![image](https://user-images.githubusercontent.com/1565058/210315627-14e46b9a-1b79-48fe-83e9-603c16630c3e.png)
- console will print "hello world"
- do the same with debug option, there is no output, the application didnt' run at all
- uninstall the plugin, restart intellij, debug works as expected

### Additional Information/Context

vlang plugin 0.0.1-beta.1

### Environment details (`v doctor` output)

```
v doctor
OS: macos, macOS, 13.0.1, 22A400
Processor: 10 cpus, 64bit, little endian, Apple M1 Max
CC version: Apple clang version 14.0.0 (clang-1400.0.29.202)

getwd: /Users/agavalda/sbx
vmodules: /Users/agavalda/.vmodules
vroot: /opt/homebrew/Cellar/vlang/0.2.4/libexec
vexe: /opt/homebrew/Cellar/vlang/0.2.4/libexec/v
vexe mtime: 2022-11-15 23:46:22
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 ddc1a1f

Git version: git version 2.37.1 (Apple Git-137.1)
Git vroot status: weekly.2022.46-5-gddc1a1fc (253 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-macos-arm64 173c526e
```

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

IntelliJ IDEA 2022.3.1 (Ultimate Edition)

**Comment by i582** [comment]
Interesting, very unexpected behavior, thanks for the feedback, I'll try to figure out why this might be happening

**Comment by i582** [comment]
Thanks for report, I've noticed that this also breaks debugging in WebStorm.
The fix is one-line, so everything should work now. There will be a release tomorrow.

**Comment by angel-git** [comment]
Thank you! ❤️
