### ISSUE TITLE
Reneming a field with the identifier `name`, attempts to rename similarily named fields in the standard library files.

### ISSUE THREAD

**Issue by MineBill** [intellij-v/intellij-v#372]
### Describe the bug

Using the identifier `name` as field will result in two issues:
- Renaming the field will attempt to rename fields in the standard library.
- Shows incorrect interface implementation of interfaces defined in test files in the standard library.

### Expected Behavior

Renaming the field should work as expected.
I'm not very familiar with V to know which code should be considered when showing interfaces that a struct implements but including test folder in `v/test` seems like a bug.

### Renaming the field will attempt to rename fields in the standard library:
![image](https://user-images.githubusercontent.com/30367251/211611737-7af92128-2873-407b-ad51-8478235a3036.png)
Trying to rename the field by right clicking and then selecting *Refactor* -> *Rename...* will result in this:
![image](https://user-images.githubusercontent.com/30367251/211612081-8bdf6645-2000-4a6b-8633-342d3cf67349.png)
![image](https://user-images.githubusercontent.com/30367251/211613576-5256dc94-1856-4fa4-901b-2db45ceb42d8.png)

### Incorrect interface implementations of interfaces defined in test files in the standard library.
![image](https://user-images.githubusercontent.com/30367251/211612702-1a7d6737-8caa-4b7f-93db-0c31b5ec9b10.png)

However, using a different name like `short_name` which is also used in the same struct `Module` as `name`, like in the second screenshot above eliminates both issues:
![image](https://user-images.githubusercontent.com/30367251/211614740-a9ca7528-6ace-4755-9aa8-4ccbd0495fc0.png)
*(Note how it doesn't show any incorrect interface implementations and any attempted refactoring completes without issues)*

### Reproduction Steps

- Create a new project using the `V Generator` in IntelliJ IDEA included in this plugin.
- Paste the following code snippet:
```v
module main

struct Person {
	name string
	age int
}

fn main() {
	john := Person{age: 50}
	println(john.age)
	println(john.name)
}
```

### Environment details (`v doctor` output)

```
OS: windows, Microsoft Windows 11 Pro v22621 64-bit
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: cc --version

getwd: C:\Users\MineBill
vmodules: C:\Users\MineBill\.vmodules
vroot: C:\Users\MineBill\Downloads\v
vexe: C:\Users\MineBill\Downloads\v\v.exe
vexe mtime: 2023-01-02 13:05:50
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 f71572a

Git version: git version 2.39.0.windows.2
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false
thirdparty/tcc: N/A
```

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

IDEA Community

**Comment by i582** [comment]
Thank you for such a detailed issue! I fixed it in a recent commit!
