### ISSUE TITLE
Global variables are not globally identifiable(bug report summary)

### ISSUE THREAD

**Issue by 32ns** [intellij-v/intellij-v#373]
### Describe the bug

![image](https://user-images.githubusercontent.com/1725120/212082127-895da0ff-4d77-4247-aa16-19618b5d69a9.png)
![image](https://user-images.githubusercontent.com/1725120/212082174-35d03de8-871f-4977-89c3-c998cbeeb740.png)

### Expected Behavior

.

### Current Behavior

.

### Reproduction Steps

.

### Environment details (`v doctor` output)

.

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

cl

**Comment by 32ns** [comment]
It has not been updated for a long time. Simple V is OK, but it can't be used when it comes to C most of the time

**Comment by i582** [comment]
Thank you! This is indeed a problem, global variables were not made entirely. Now they should work better. If there are any problems, then create an issue and I will fix it.
