### ISSUE TITLE
Some auto-completions don't work

### ISSUE THREAD

**Issue by RIC217** [intellij-v/intellij-v#378]
### Describe the bug

There are some auto-complete suggestions that don't work :
![image](https://user-images.githubusercontent.com/68387948/216142805-43ef3dc1-736f-4e2a-91d2-f5c3c989fb77.png)
![image](https://user-images.githubusercontent.com/68387948/216142935-4a356604-4d33-4dfc-8bb9-7fcd26411643.png)

![image](https://user-images.githubusercontent.com/68387948/216410510-0431482e-78ef-46c8-9e90-a7de876ce3fb.png)

### Expected Behavior

Auto-complete suggestions to work

### Current Behavior

No suggestions

### Reproduction Steps

Create a structure and see if the auto-complete suggestion works for the elements of the structure

### Environment details (`v doctor` output)

OS: linux, Ubuntu 22.10
Processor: 2 cpus, 64bit, little endian, Intel(R) Celeron(R) N4020 CPU @ 1.10GHz
CC version: cc (Ubuntu 12.2.0-3ubuntu1) 12.2.0

getwd: /home/riccardo
vmodules: /home/riccardo/.vmodules
vroot: /home/riccardo/v
vexe: /home/riccardo/v/v
vexe mtime: 2023-01-30 19:58:25
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 bb512f7.6b20c57

Git version: git version 2.37.2
Git vroot status: weekly.2023.04-34-g6b20c572 (16 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

Intellij Idea Ultimate

**Comment by i582** [comment]
Yes, this is a known issue, thanks for letting me know! Fixed. I will try to upload a micro update today.
