### ISSUE TITLE
Add embedded structs in completion variants

### ISSUE THREAD

**Issue by i582** [intellij-v/intellij-v#383]
### Describe the feature

.

### Use Case

.

### Version used

.

### Environment details (`v doctor` output)

.

**Comment by 32ns** [comment]
It's getting better and better! 👍👍👍

**Comment by i582** [comment]
> It's getting better and better! 👍👍👍

@32ns thank you! If you have any ideas what else can be added, write, I will be very grateful!

**Comment by 32ns** [comment]
vlang is not mature in practical application, so I switch back to Qt for the time being. However, I like its syntax very much, so I will always pay attention to it. I hope Vlang and intellij-v can improve quickly and let more people feel its charm,Thank you for your open source efforts!

**Comment by i582** [comment]
> vlang is not mature in practical application

It's true, I'm currently writing my VLS and it's a pain...

**Comment by i582** [comment]
@32ns good luck with your projects, hope to see you again!
