### ISSUE TITLE
Error Option message for structure optional field

### ISSUE THREAD

**Issue by ArtemkaKun** [intellij-v/intellij-v#385]
### Describe the bug

Optional structure fields and first-class optional variables were implemented. The plugin needs to be updated with these new features and not show error anymore in a few cases.

### Expected Behavior

No error

### Current Behavior

![image](https://user-images.githubusercontent.com/36485221/220696464-2e927029-20f3-4146-afd7-f6d7810154c7.png)

### Reproduction Steps

```v
struct Node {
	location NodeLocation [json: 'loc']
}

struct NodeLocation {
	offset ?int
}

//...

if node.location.offset == none {}
```

### Environment details (`v doctor` output)

```
OS: linux, "Garuda Linux"
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 3800X 8-Core Processor
CC version: cc (GCC) 12.2.1 20230201

getwd: /home/yuart
vmodules: /home/yuart/.vmodules
vroot: /home/yuart/Projects/v
vexe: /home/yuart/Projects/v/v
vexe mtime: 2023-02-22 16:38:40
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 d971d93.2879afa

Git version: git version 2.39.2
Git vroot status: weekly.2023.07-34-g2879afad
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

Intellij Idea Ultimate

**Comment by i582** [comment]
Hi
Thanks for the report! I plan to refactor the Option handling in the plugin in the early March release.
