### ISSUE TITLE
(bug report summary)

### ISSUE THREAD

**Issue by 32ns** [intellij-v/intellij-v#475]
### Describe the bug

There seems to be a problem with the submission recently. I can't pull it down

![image](https://user-images.githubusercontent.com/1725120/222343191-77f572dc-2edd-4bbb-9b63-3a7e31716a39.png)

### Expected Behavior

.

### Current Behavior

.

### Reproduction Steps

.

### Possible Solution

.

### Additional Information/Context

.

### Environment details (`v doctor` output)

.

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

.

**Comment by i582** [comment]
Ah, sorry, try again

**Comment by 32ns** [comment]
Yes, thank you

**Comment by i582** [comment]
@32ns did this solve the problem?

**Comment by 32ns** [comment]
> @32ns这是否解决了问题？
Yes, thank you very much, but there are still some problems with pulling

![image](https://user-images.githubusercontent.com/1725120/222727388-c72e9357-17a5-4074-919f-7ae2d0430c90.png)

**Comment by i582** [comment]
@32ns please, try again

**Comment by 32ns** [comment]
> @32ns请再试一次
That's it. No problem
