### ISSUE TITLE
Debugger shows (double) instead of (f64)

### ISSUE THREAD

**Issue by danieldaeschle** [intellij-v/intellij-v#501]
### Describe the bug

![image](https://user-images.githubusercontent.com/30751516/223671326-1a2dc238-2b4b-4b73-9cac-6a8cac91e1c3.png)
The debugger shows type (double). But in V there is no double. It should be f64.

### Expected Behavior

It should be f64.

### Current Behavior

It shows double.

### Reproduction Steps

See screenshot.

### Environment details (`v doctor` output)

OS: windows, Microsoft Windows 11 Home v22621 64-bit
Processor: 16 cpus, 64bit, little endian, 
CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: cc --version

getwd: C:\Users\Daniel\Projects\v
vmodules: C:\Users\Daniel\.vmodules
vroot: C:\Users\Daniel\Projects\v
vexe: C:\Users\Daniel\Projects\v\v.exe
vexe mtime: 2023-03-08 09:07:59
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 2597efa.476b1bf

Git version: git version 2.39.2.windows.1
Git vroot status: weekly.2023.10-13-g476b1bf4
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 e90c2620

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

CLion

**Comment by i582** [comment]
Indeed! Great find, thank you!

**Comment by i582** [comment]
Same for float

**Comment by i582** [comment]
hmm, it seems Windows specific problem

macOS:
<img width="167" alt="Снимок экрана 2023-03-08 в 14 17 24" src="https://user-images.githubusercontent.com/51853996/223686571-c1f52fbc-8c5d-429f-a5e2-1aeb0dc8454b.png">

**Comment by i582** [comment]
`i64` on Windows:

<img width="200" alt="Снимок экрана 2023-03-08 в 14 35 13" src="https://user-images.githubusercontent.com/51853996/223690509-986c14a5-9842-4a8b-ab57-3d4105789321.png">

**Comment by danieldaeschle** [comment]
Thanks for verifying!

**Comment by i582** [comment]
Will be fixed in a minor release when the 2023.1 version of the IDE is released (around March 15th).
