### ISSUE TITLE
module name error

### ISSUE THREAD

**Issue by danieldaeschle** [intellij-v/intellij-v#502]
### Describe the bug

![image](https://user-images.githubusercontent.com/30751516/223712454-50a4d2cc-416c-4f7d-a2a1-148d30036663.png)

### Expected Behavior

It shouldn't be an error because v.mod contains the actual module name.

### Current Behavior

It shows an error.

### Reproduction Steps

https://github.com/danieldaeschle/vjwt

### Possible Solution

It should consider v.mod file at root level.

### Environment details (`v doctor` output)

OS: windows, Microsoft Windows 11 Home v22621 64-bit
Processor: 16 cpus, 64bit, little endian,
CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
cmd: cc --version

getwd: C:\Users\Daniel\Projects\v
vmodules: C:\Users\Daniel.vmodules
vroot: C:\Users\Daniel\Projects\v
vexe: C:\Users\Daniel\Projects\v\v.exe
vexe mtime: 2023-03-08 09:07:59
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 2597efa.476b1bf

Git version: git version 2.39.2.windows.1
Git vroot status: weekly.2023.10-13-g476b1bf4
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 e90c2620

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

CLion

**Comment by i582** [comment]
Hi
I will remove this check for modules in the root folder
Thank you for feedback!
