### ISSUE TITLE
Debugging is ineffective on the Windows system.

### ISSUE THREAD

**Issue by xiusin** [intellij-v/intellij-v#504]
### Describe the bug

![image](https://user-images.githubusercontent.com/36065131/224458053-674cab97-ca3c-4a6b-b9c4-65c5e6e90cb0.png)

> Or, how can I solve it?

### Expected Behavior

success

### Current Behavior

ineffective 

### Reproduction Steps

none

### Environment details (`v doctor` output)

```
OS: windows, Microsoft Windows 11 רҵ�� v22621 64 λ
Processor: 4 cpus, 64bit, little endian,
CC version: clang version 16.0.0 (https://github.com/llvm/llvm-project.git 124f90bd89b97066e01274a9bba1068f3a175d66)

getwd: C:\Users\chenc
vmodules: C:\Users\chenc\.vmodules
vroot: D:\Program Files\v
vexe: D:\Program Files\v\v.exe
vexe mtime: 2023-03-09 14:11:21
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 737e7f6.71c3b66

Git version: git version 2.39.2.windows.1
Git vroot status: weekly.2023.10-20-g71c3b66e (8 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 e90c2620
```

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

goland

**Comment by i582** [comment]
Hmm, is MSVC installed? Because debug only works with it on Windows.

**Comment by xiusin** [comment]
Okay, I'll take another look.
