### ISSUE TITLE
Autocompletion in function params

### ISSUE THREAD

**Issue by danieldaeschle** [intellij-v/intellij-v#510]
### Describe the feature

![image](https://user-images.githubusercontent.com/30751516/224546717-359916c5-2fc8-426b-9956-15ba2b2f7437.png)
When having Params struct and a parameter is an enum there is no autocompletion.

### Use Case

.

**Comment by i582** [comment]
Hi
Apparently the problem is that plugin could not find the definition of the `algorithn` field, which is why there are no autocompletion.
Can you send the whole project?

**Comment by danieldaeschle** [comment]
It's danieldaeschle/vjwt

**Comment by i582** [comment]
🎉 
<img width="295" alt="Снимок экрана 2023-03-14 в 10 50 57" src="https://user-images.githubusercontent.com/51853996/224918839-f864ef6f-f16e-4e25-86a5-1797f3ace85c.png">
