### ISSUE TITLE
wrong type when debugging (function from map)

### ISSUE THREAD

**Issue by danieldaeschle** [intellij-v/intellij-v#524]
### Describe the bug

![image](https://user-images.githubusercontent.com/30751516/224955458-7acbca78-4ff9-42e8-b798-cf54e1fea187.png)

Displays main.exe`main__test

![image](https://user-images.githubusercontent.com/30751516/224955742-54d1cf79-ef03-40c1-98e5-623c0911ec48.png)

Displays completely wrong name

### Expected Behavior

Display nicer name like: 'main.test'

### Current Behavior

.

### Reproduction Steps

.

### Environment details (`v doctor` output)

.

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

CLion

**Comment by i582** [comment]
Thank you! Also, a plugin should not show void as a return type.

**Comment by i582** [comment]
Same for C code:
<img width="529" alt="Снимок экрана 2023-03-14 в 13 33 28" src="https://user-images.githubusercontent.com/51853996/224958065-e1e8482d-2593-4602-8464-4d9457e6c1ed.png">

**Comment by i582** [comment]
@danieldaeschle what do you think?

<img width="735" alt="Снимок экрана 2023-03-14 в 14 05 47" src="https://user-images.githubusercontent.com/51853996/224966710-363af54b-af06-4a7f-aae4-6b738f24c895.png">

**Comment by i582** [comment]
Map of functions is not working :(

<img width="868" alt="Снимок экрана 2023-03-14 в 14 21 30" src="https://user-images.githubusercontent.com/51853996/224970655-9e675907-ad7f-415e-a800-726779916ae4.png">

**Comment by danieldaeschle** [comment]
looks good!
