### ISSUE TITLE
`fmt` inserts blank line between documentation comment and function declaration

### ISSUE THREAD

**Issue by ArtemkaKun** [intellij-v/intellij-v#532]
### Describe the bug

When using `vmt` on an unformatted file, which contains a properly formatted documentation comment for a function, it will insert a blank line between a function declaration and a documentation comment.

### Expected Behavior

`vfm` does not insert a blank line between a properly formatted documentation comment and a function declaration

### Current Behavior

`vfm` inserts a blank line between a properly formatted documentation comment and a function declaration and breaks the documentation

### Reproduction Steps

```v
unformatted_code := f32(                   1.0
)

// my_method Is cool!
fn my_method() {
    println('Cool!')
}
```

### Additional Information/Context

1. I have "Format on save" turned on in IDE
2. This bug doesn't exist in Playground

### Environment details (`v doctor` output)

```
V full version: V 0.3.3 d7a418f.93b7cc4
OS: linux, "Garuda Linux"
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 3800X 8-Core Processor

getwd: /home/yuart
vexe: /home/yuart/Projects/v/v
vexe mtime: 2023-03-21 14:32:14

vroot: OK, value: /home/yuart/Projects/v
VMODULES: OK, value: /home/yuart/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.40.0
Git vroot status: weekly.2023.12-9-g93b7cc48 (14 commit(s) behind V master)
.git/config present: true

CC version: cc (GCC) 12.2.1 20230201
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

Intellij IDEA Ultimate

**Comment by SolarWolf-Code** [comment]
@ArtemkaKun Are you suggesting the output after formatting is something like this?
```v
unformatted_code := f32(1.0)

// my_method Is cool!

fn my_method() {
	println('Cool!')
}

```
If so, I just tested on my end and it seems to be working for me. Although I do see "no usages" in-between the two:
![image](https://user-images.githubusercontent.com/54452723/227757444-4c3f1c56-ae4f-4f4a-acfb-ec2e636efe2e.png)

**Comment by ArtemkaKun** [comment]
Hi, the code after formatting must be like this

```v
unformatted_code := f32(1.0)

// my_method Is cool!
fn my_method() {
	println('Cool!')
}
```

No, I didn't confuse it with "used by" text, it's clearly wisible that comment and function declaration are separated by blank line and IDE stops treat the comment as this method documentation 

Also - did you format the code manually via `v fmt` or turned on "Format on save" and saved the file?

**Comment by SolarWolf-Code** [comment]
Hmm odd. I used the "Format on Save" and saved the file which seemed to not leave a gap. Did you try reinstalling the plugin?

**Comment by ArtemkaKun** [comment]
Seems the problem on my side only. I will try to tinker things and will report if something changed

**Comment by ArtemkaKun** [comment]
Reinstallation and other shenanigans didn't help

**Comment by ArtemkaKun** [comment]
There is a [video](https://youtu.be/NtgFdOxeZnw) how it look's like on my side

**Comment by SolarWolf-Code** [comment]
I think I see the problem. I believe you are using the IDE's reformatting and not the plugins. When you select "V" inside the IDE's "Format On Save" it is basically just allowing the Intellij reformatting to work on that file type. Can you try to turn that off and turn on this setting instead:
![image](https://user-images.githubusercontent.com/54452723/228082928-79fa16a5-7866-433f-a312-2914a0defdad.png)
To get there: File > Settings (or ctrl + alt + s) > Languages and Frameworks > V > Vfmt

**Comment by ArtemkaKun** [comment]
Thanks, that resolved the problem :) Not sure why the Search in Settings doesn't find the "Run vfmt on Save" option when searching for "Save" word
